[package]
name = "spatialos-sdk"
version = "0.1.1"
authors = ["Thomas Nicollet <thomas.nicollet@epitech.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spatialos-sys = "0.0.4"
